### ISSUE TITLE
UI suggestions!

### ISSUE THREAD

**Issue by MaxProfit** [roshinis78/intro-to-me#1]
Hey Roshini,

Just saw your awesome online profile! It would be cool instead of just clicking on the back arrow if you could click off of any of the components (like the deadspace) and it would take you back to the main menu. I just think that'd be neat!

**Comment by roshinis78** [comment]
Oooh yeah that would definitely be cool!! Thanks for the suggestion Matt, I'll let you know when I've updated it (probably by tomorrow evening) 😄

**Comment by roshinis78** [comment]
Cool, I added the functionality by wrapping the page content in a div and using the following code! But I might tweak this a bit tomorrow because on my iPad specifically, some of the links don't always work.

```js
toMenu (event) {
    let isNotContent = $(event.target).parents(".content").length === 0;
    if(this.state.name !== "Nav" && isNotContent) {
      this.setState({name: "Nav"});
    }
}
```
